//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int user_id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string name { get; set; }

        [Range(1, 120, ErrorMessage = "Age is out of range")]
        public Nullable<int> age { get; set; }
    }
}
